services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $localDatabase: '@In2code.In2publishCore.Database.Local'

  In2code\In2publishCore\Features\PreventParallelPublishing\:
    resource: '../../../Classes/Features/PreventParallelPublishing/*'

  In2code\In2publishCore\Features\PreventParallelPublishing\Service\RunningRequestService:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-RunningRequestService-RecursiveRecordPublishingBegan'
        method: 'onRecursiveRecordPublishingBegan'
        event: In2code\In2publishCore\Event\RecursiveRecordPublishingBegan
      - name: event.listener
        identifier: 'in2publishcore-RunningRequestService-VoteIfRecordIsPublishable'
        method: 'isPublishable'
        event: In2code\In2publishCore\Event\VoteIfRecordIsPublishable
      - name: event.listener
        identifier: 'in2publishcore-RunningRequestService-DetermineIfRecordIsPublishing'
        method: 'isPublishing'
        event: In2code\In2publishCore\Event\DetermineIfRecordIsPublishing
