services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $localDatabase: '@In2code.In2publishCore.Database.Local'

  In2code\In2publishCore\Features\FullTablePublishing\:
    resource: '../../../Classes/Features/FullTablePublishing/*'
    exclude:
      - '../../../Classes/Features/FullTablePublishing/Command/Local/*'

  In2code\In2publishCore\Features\FullTablePublishing\Command\BackupCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:fulltablepublishing:backup'
        description: Creates a sql backup of the given table.
