services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Component\RemoteCommandExecution\:
    resource: '../../../Classes/Component/RemoteCommandExecution/*'

  In2code\In2publishCore\Component\RemoteCommandExecution\RemoteAdapter\AdapterInterface:
    factory: [ '@In2code\In2publishCore\Component\RemoteCommandExecution\RemoteAdapter\RemoteAdapterRegistry', 'createSelectedAdapter' ]

  In2code\In2publishCore\Component\RemoteCommandExecution\RemoteAdapter\RemoteAdapterRegistry:
    public: true
