services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $localDatabase: '@In2code.In2publishCore.Database.Local'
      $localRepository: '@In2code.In2publishCore.Features.SimplifiedOverviewAndPublishing.LocalDatabaseRepository'
      $foreignRepository: '@In2code.In2publishCore.Features.SimplifiedOverviewAndPublishing.ForeignDatabaseRepository'

  In2code\In2publishCore\Component\TcaHandling\:
    resource: '../../../Classes/Component/TcaHandling/*'

  In2code\In2publishCore\Component\TcaHandling\PreProcessing\TcaPreProcessingService:
    public: true

  In2code\In2publishCore\Component\TcaHandling\RecordIndex:
    shared: true
    public: true
