services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $cache: '@cache.in2publish_core'
      $localDatabase: '@In2code.In2publishCore.Database.Local'
      $foreignDatabase: '@In2code.In2publishCore.Database.Foreign'
      $localRepository: '@In2code.In2publishCore.Component.TcaHandling.LocalDatabaseRepository'
      $foreignRepository: '@In2code.In2publishCore.Component.TcaHandling.ForeignDatabaseRepository'

  In2code\In2publishCore\Component\TcaHandling\:
    resource: '../../../Classes/Component/TcaHandling/*'

  In2code\In2publishCore\Component\TcaHandling\PreProcessing\TcaPreProcessingService:
    public: true

  In2code\In2publishCore\Component\TcaHandling\RecordIndex:
    shared: true
    public: true

  'In2code.In2publishCore.Component.TcaHandling.LocalDatabaseRepository':
    class: 'In2code\In2publishCore\Component\TcaHandling\Repository\SingleDatabaseRepository'
    arguments:
      $connection: '@In2code.In2publishCore.Database.Local'

  'In2code.In2publishCore.Component.TcaHandling.ForeignDatabaseRepository':
    class: 'In2code\In2publishCore\Component\TcaHandling\Repository\SingleDatabaseRepository'
    arguments:
      $connection: '@In2code.In2publishCore.Database.Foreign'

  In2code\In2publishCore\Component\TcaHandling\FileHandling\FileRecordListener:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-FileRecordListener-RecordWasCreated'
        method: 'onRecordWasCreated'
        event: In2code\In2publishCore\Event\RecordWasCreated
      - name: event.listener
        identifier: 'in2publishcore-FileRecordListener-RecordRelationsWereResolved'
        method: 'onRecordRelationsWereResolved'
        event: In2code\In2publishCore\Event\RecordRelationsWereResolved
