services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\RecordInspector\:
    resource: '../../../Classes/Features/RecordInspector/*'

  In2code\In2publishCore\Features\RecordInspector\Controller\RecordInspectorController:
    tags:
      - name: 'in2publish_core.admin_tool'
        title: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.record_inspector'
        description: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.record_inspector.description'
        actions: 'index,inspect'
