services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\SkipEmptyTable\:
    resource: '../../../Classes/Features/SkipEmptyTable/*'

  In2code\In2publishCore\Features\SkipEmptyTable\SkipTableVoter:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-SkipTableVoter-VoteIfSearchingForRelatedRecordsByTableShouldBeSkipped'
        method: 'shouldSkipSearchingForRelatedRecordByTable'
        event: In2code\In2publishCore\Event\VoteIfSearchingForRelatedRecordsByTableShouldBeSkipped
