services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Component\RemoteProcedureCall\:
    resource: '../../../Classes/Component/RemoteProcedureCall/*'
    exclude:
      - '../../../Classes/Component/RemoteProcedureCall/Command/Foreign/*'
