services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      array $extConf: '@=service("TYPO3\\CMS\\Core\\Configuration\\ExtensionConfiguration").get("in2publish_core")'

  In2code\In2publishCore\Component\ConfigContainer\:
    resource: '../../../Classes/Component/ConfigContainer/*'

  In2code\In2publishCore\Component\ConfigContainer\Provider\PageTsProvider:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-PageTsProvider-bootCompleted'
        method: 'processData'
        event: In2code\In2publishCore\Event\ExtTablesPostProcessingEvent
