services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\AdminTools\:
    resource: '../../../Classes/Features/AdminTools/*'

  In2code\In2publishCore\Features\AdminTools\Service\ToolsRegistry:
    tags:
      - name: 'event.listener'
        identifier: 'in2publish_core-ToolsRegistry-BootCompletedEvent'
        event: 'In2code\In2publishCore\Event\ExtTablesPostProcessingEvent'
        method: 'processData'

  In2code\In2publishCore\Features\AdminTools\Controller\LetterboxController:
    tags:
      - name: 'in2publish_core.admin_tool'
        title: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.flush_envelopes'
        description: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.flush_envelopes.description'
        actions: 'index,flushEnvelopes'

  In2code\In2publishCore\Features\AdminTools\Controller\RegistryController:
    tags:
      - name: 'in2publish_core.admin_tool'
        title: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.flush_registry'
        description: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.flush_registry.description'
        actions: 'index,flushRegistry'

  In2code\In2publishCore\Features\AdminTools\Controller\TcaController:
    tags:
      - name: 'in2publish_core.admin_tool'
        title: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.tca'
        description: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.tca.description'
        actions: 'index'

  In2code\In2publishCore\Features\AdminTools\Controller\ShowConfigurationController:
    tags:
      - name: 'in2publish_core.admin_tool'
        title: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.configuration'
        description: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.configuration.description'
        actions: 'index'

  In2code\In2publishCore\Features\AdminTools\Controller\TestController:
    tags:
      - name: 'in2publish_core.admin_tool'
        title: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.test'
        description: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.test.description'
        actions: 'index'

  In2code\In2publishCore\Features\AdminTools\Controller\ToolsController:
    tags:
      - name: 'in2publish_core.admin_tool'
        title: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.index'
        description: 'LLL:EXT:in2publish_core/Resources/Private/Language/locallang.xlf:moduleselector.index.description'
        actions: 'index'
        before: '*'
