services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Component\TemporaryAssetTransmission\:
    resource: '../../../Classes/Component/TemporaryAssetTransmission/*'

  In2code\In2publishCore\Component\TemporaryAssetTransmission\TransmissionAdapter\AdapterInterface:
    factory: [ '@In2code\In2publishCore\Component\TemporaryAssetTransmission\TransmissionAdapter\TransmissionAdapterRegistry', 'createSelectedAdapter' ]

  In2code\In2publishCore\Component\TemporaryAssetTransmission\TransmissionAdapter\TransmissionAdapterRegistry:
    public: true
